import { PrismaClient } from '@prisma/client';

const prisma = new PrismaClient();

async function main() {
  const blackCards = [
    { text: 'Lo que más me gusta hacer en las mañanas es_________' },
    { text: 'Lo mejor del fin de semana es_________________' },
    { text: 'Lo peor del lunes es_________________' },
    { text: 'Lo que más le gusta a un argentino es_____________________' },
    { text: 'Lo que más le gusta al (jugador de tu derecha) es ___________________________' },
    { text: 'El otro día estaba caminando y me encontré con________________________' },
    { text: 'La peor cita que tuve terminó con_________________' },
    { text: 'Lo que nunca falta en una fiesta es_________________' },
    { text: 'Lo mejor de ser adulto es_________________' },
    { text: 'Lo más vergonzoso que me pasó fue_________________' },
    { text: 'Lo que me da más miedo es_________________' },
    { text: 'La excusa más ridícula que he usado es_________________' },
    { text: 'Lo que siempre me hace reír es_________________' },
    { text: 'La última vez que lloré fue por_________________' },
    { text: 'Lo que más odio de mi trabajo es_________________' },
    { text: 'El mejor regalo que he recibido es_________________' },
    { text: 'Lo peor que he hecho por amor es_________________' },
    { text: 'Lo más raro que me gusta comer es_________________' },
    { text: 'Lo más divertido que he hecho borracho es_________________' },
    { text: 'Lo primero que hago al llegar a casa es_________________' },
    { text: 'Lo que más extraño de mi infancia es_________________' },
    { text: 'Mi secreto más oscuro es_________________' },
    { text: 'Lo más loco que he hecho en vacaciones es_________________' },
    { text: 'Lo peor que me ha pasado en el transporte público es_________________' },
    { text: 'La última vez que me sentí muy avergonzado fue por_________________' },
    { text: 'Lo más extraño que he coleccionado es_________________' },
    { text: 'La mejor película que he visto es_________________' },
    { text: 'Lo más peligroso que he hecho es_________________' },
    { text: 'Lo más caro que he comprado es_________________' },
    { text: 'La peor comida que he probado es_________________' },
    { text: 'Lo que nunca entenderé es_________________' },
    { text: 'Lo que más me irrita es_________________' },
    { text: 'La mejor fiesta en la que he estado fue_________________' },
    { text: 'Lo que más me sorprende de la gente es_________________' },
    { text: 'Lo más tonto que he hecho por una apuesta es_________________' },
    { text: 'Lo que más me gusta de mi ciudad es_________________' },
    { text: 'La última vez que me sentí muy feliz fue por_________________' },
    { text: 'Lo más vergonzoso que he dicho en público es_________________' },
    { text: 'Lo mejor de los domingos es_________________' },
    { text: 'Lo más raro que he visto en internet es_________________' },
    { text: 'La última vez que me reí a carcajadas fue por_________________' },
    { text: 'Lo que más me gusta de mis amigos es_________________' },
    { text: 'Lo que siempre me hace enojar es_________________' },
    { text: 'Lo más importante que he aprendido es_________________' },
    { text: 'Lo peor que he hecho en una entrevista de trabajo es_________________' },
    { text: 'Lo más emocionante que he vivido es_________________' },
    { text: 'Lo que más disfruto de mi tiempo libre es_________________' },
    { text: 'La última vez que me sentí muy valiente fue por_________________' },
    { text: 'Lo que siempre me motiva es_________________' },
    { text: 'Lo más extraño que he soñado es_________________' },
 { text: 'Lo más extraño que he visto en mi barrio es_________________' },
    { text: 'La última vez que me quedé sin palabras fue cuando_________________' },
    { text: 'Lo mejor de mi infancia fue_________________' },
    { text: 'La última vez que me metí en problemas fue por_________________' },
    { text: 'Lo más ridículo que he hecho por dinero es_________________' },
    { text: 'Lo que siempre me hace llorar es_________________' },
    { text: 'El peor consejo que he seguido fue_________________' },
    { text: 'Lo que más me molesta de la televisión es_________________' },
    { text: 'Lo más raro que he hecho en una primera cita es_________________' },
    { text: 'Lo que nunca le diría a mi jefe es_________________' },
    { text: 'La última vez que me sentí muy orgulloso fue por_________________' },
    { text: 'Lo más embarazoso que me pasó en la escuela fue_________________' },
    { text: 'Lo que más me gusta hacer en mi tiempo libre es_________________' },
    { text: 'Lo más absurdo que he comprado es_________________' },
    { text: 'La última vez que hice algo ilegal fue cuando_________________' },
    { text: 'Lo que siempre me sorprende de mi familia es_________________' },
    { text: 'La última vez que me perdí fue en_________________' },
    { text: 'Lo más asqueroso que he probado es_________________' },
    { text: 'Lo que siempre olvido hacer es_________________' },
    { text: 'Lo más extraño que he visto en mis vacaciones es_________________' },
    { text: 'La última vez que me reí tanto que lloré fue cuando_________________' },
    { text: 'Lo que más me irrita de la gente es_________________' },
    { text: 'La mejor broma que he hecho es_________________' },
    { text: 'Lo más peligroso que he visto es_________________' },
    { text: 'Lo más raro que he hecho en un sueño es_________________' },
    { text: 'Lo que nunca pensé que haría es_________________' },
    { text: 'La última vez que me avergoncé en público fue por_________________' },
    { text: 'Lo más divertido de mi trabajo es_________________' },
    { text: 'Lo que más me gusta de mis fines de semana es_________________' },
    { text: 'Lo más aterrador que me ha pasado es_________________' },
    { text: 'La última vez que me quedé despierto toda la noche fue por_________________' },
    { text: 'Lo que siempre me hace sonreír es_________________' },
    { text: 'La peor experiencia en un restaurante fue_________________' },
    { text: 'Lo más extraño que he visto en el metro es_________________' },
    { text: 'Lo más incómodo que me ha pasado en una reunión familiar es_________________' },
    { text: 'Lo más divertido que he hecho en una fiesta es_________________' },
    { text: 'La última vez que me sentí muy inspirado fue por_________________' },
    { text: 'Lo más ridículo que he hecho por amor es_________________' },
    { text: 'Lo que siempre me hace sentir nostálgico es_________________' },
    { text: 'La peor decisión que he tomado fue_________________' },
    { text: 'Lo más extraño que he visto en la televisión es_________________' },
    { text: 'Lo que nunca olvidaré de mi infancia es_________________' },
    { text: 'Lo más raro que he hecho en una fiesta es_________________' },
    { text: 'La última vez que me arrepentí de algo fue cuando_________________' },
    { text: 'Lo más curioso que he aprendido es_________________' },
    { text: 'Lo más vergonzoso que he hecho en público es_________________' },
    { text: 'Lo que siempre me anima es_________________' },
    { text: 'La última vez que hice algo estúpido fue por_________________' },
    { text: 'Lo más extraño que he visto en una tienda es_________________' },
    { text: 'La peor excusa que he escuchado para faltar al trabajo es_________________' },
    { text: 'Lo que más me hace reír en los funerales es_________________' },
    { text: 'La peor manera de terminar una relación es_________________' },
    { text: 'Lo más inapropiado que he dicho en una boda es_________________' },
    { text: 'La última vez que me reí en un momento serio fue cuando_________________' },
    { text: 'Lo más incómodo que he visto en una fiesta es_________________' },
    { text: 'Lo más insensible que he hecho es_________________' },
    { text: 'Lo peor que he deseado a alguien es_________________' },
    { text: 'La broma más cruel que he hecho es_________________' },
    { text: 'Lo más inapropiado que he dicho en el trabajo es_________________' },
    { text: 'La peor cosa que he hecho por dinero es_________________' },
    { text: 'Lo más vergonzoso que he dicho borracho es_________________' },
    { text: 'La cosa más ofensiva que me han dicho es_________________' },
    { text: 'Lo más cruel que he pensado es_________________' },
    { text: 'Lo más inapropiado que he hecho en público es_________________' },
    { text: 'La peor manera de arruinar una fiesta es_________________' },
    { text: 'Lo más inapropiado que he visto en el internet es_________________' },
    { text: 'La cosa más horrible que he encontrado en mi comida es_________________' },
    { text: 'Lo más insensible que he dicho a un amigo es_________________' },
    { text: 'La peor mentira que he contado es_________________' },
    { text: 'Lo más ofensivo que he encontrado en las redes sociales es_________________' },
    { text: 'La última vez que me reí de una tragedia fue cuando_________________' },
    { text: 'Lo más inapropiado que he hecho en una primera cita es_________________' },
    { text: 'La peor cosa que he dicho a un desconocido es_________________' },
    { text: 'Lo más cruel que he hecho por celos es_________________' },
    { text: 'La peor cosa que he hecho en una reunión familiar es_________________' },
    { text: 'Lo más inapropiado que he visto en una boda es_________________' },
    { text: 'La cosa más ofensiva que he encontrado en una fiesta es_________________' },
    { text: 'Lo más insensible que he hecho en una emergencia es_________________' },
    { text: 'La peor manera de romper una amistad es_________________' },
    { text: 'Lo más inapropiado que he dicho en una reunión de trabajo es_________________' },
    { text: 'La peor cosa que he pensado sobre alguien es_________________' },
    { text: 'Lo más cruel que he dicho a mi pareja es_________________' },
    { text: 'Lo más ofensivo que he hecho en público es_________________' },
    { text: 'La cosa más inapropiada que he encontrado en la casa de alguien es_________________' },
    { text: 'La peor broma que he hecho en el trabajo es_________________' },
    { text: 'Lo más insensible que he dicho en un hospital es_________________' },
    { text: 'Lo peor que he deseado a mi jefe es_________________' },
    { text: 'La cosa más inapropiada que he visto en la calle es_________________' },
    { text: 'Lo más cruel que he dicho en una discusión es_________________' },
    { text: 'La peor cosa que he hecho a un compañero de trabajo es_________________' },
    { text: 'Lo más ofensivo que he pensado sobre un familiar es_________________' },
    { text: 'La cosa más inapropiada que he hecho en una biblioteca es_________________' },
    { text: 'Lo más insensible que he dicho en una reunión familiar es_________________' },
    { text: 'La peor cosa que he hecho en una fiesta de cumpleaños es_________________' },
    { text: 'Lo más cruel que he hecho por venganza es_________________' },
    { text: 'La cosa más ofensiva que he dicho en una entrevista es_________________' },
    { text: 'Lo más inapropiado que he dicho en un funeral es_________________' },
    { text: 'La peor cosa que he hecho a un amigo es_________________' },
    { text: 'Lo más oscuro que he visto en el subte es_________________' },
    { text: 'La peor cosa que puede pasar en una marcha es_________________' },
    { text: 'Lo más bizarro que he visto en la calle Corrientes es_________________' },
    { text: 'El peor chiste que he escuchado en un asado es_________________' },
    { text: 'Lo más extraño que he visto en la Feria de Mataderos es_________________' },
    { text: 'La peor cosa que me ha pasado en el colectivo es_________________' },
    { text: 'Lo más oscuro que he visto en la cancha es_________________' },
    { text: 'La peor cosa que he visto en una villa es_________________' },
    { text: 'Lo más raro que he comido en la Costanera es_________________' },
    { text: 'El peor piropo que he recibido en la calle Florida es_________________' },
    { text: 'Lo más oscuro que he visto en una milonga es_________________' },
    { text: 'La peor cosa que me ha pasado en una protesta es_________________' },
    { text: 'Lo más extraño que he encontrado en un boliche es_________________' },
    { text: 'El peor insulto que he recibido en el fútbol es_________________' },
    { text: 'Lo más oscuro que he visto en una noche en Buenos Aires es_________________' },
    { text: 'La peor cosa que he visto en el Rosedal es_________________' },
    { text: 'Lo más raro que he hecho en una peña es_________________' },
    { text: 'El peor accidente que he visto en la General Paz es_________________' },
    { text: 'Lo más oscuro que he visto en el Mercado de San Telmo es_________________' },
    { text: 'La peor cosa que he encontrado en un kiosco es_________________' },
    { text: 'Lo más raro que he visto en un taxi es_________________' },
    { text: 'El peor engaño que he sufrido en la calle Avellaneda es_________________' },
    { text: 'Lo más oscuro que he visto en una parrilla es_________________' },
    { text: 'La peor cosa que me ha pasado en el Tigre es_________________' },
    { text: 'Lo más raro que he visto en la Avenida de Mayo es_________________' },
    { text: 'El peor rumor que he escuchado sobre un político es_________________' },
    { text: 'Lo más oscuro que he visto en la Bombonera es_________________' },
    { text: 'La peor cosa que he visto en el Obelisco es_________________' },
    { text: 'Lo más raro que he comprado en la Salada es_________________' },
    { text: 'El peor servicio que he recibido en un restaurante es_________________' },
    { text: 'Lo más oscuro que he visto en la Plaza de Mayo es_________________' },
    { text: 'La peor cosa que he visto en el Teatro Colón es_________________' },
    { text: 'Lo más raro que he visto en el Jardín Botánico es_________________' },
    { text: 'El peor consejo que me han dado en una farmacia es_________________' },
    { text: 'Lo más oscuro que he visto en una estación de tren es_________________' },
    { text: 'La peor cosa que he visto en el Barrio Chino es_________________' },
    { text: 'Lo más raro que he encontrado en la Recoleta es_________________' },
    { text: 'El peor escándalo que he visto en la televisión argentina es_________________' },
    { text: 'Lo más oscuro que he visto en una escuela pública es_________________' },
    { text: 'La peor cosa que me ha pasado en una manifestación es_________________' },
    { text: 'Lo más raro que he visto en la Feria de San Telmo es_________________' },
    { text: 'El peor accidente que he visto en la Panamericana es_________________' },
    { text: 'Lo más oscuro que he visto en una cancha de Boca es_________________' },
    { text: 'La peor cosa que he visto en un hospital público es_________________' },
    { text: 'Lo más raro que he visto en una estación de servicio es_________________' },
    { text: 'El peor robo que he presenciado en Once es_________________' },
    { text: 'Lo más oscuro que he visto en un acto político es_________________' },
    { text: 'La peor cosa que he encontrado en una librería es_________________' },
    { text: 'Lo más raro que he visto en la Reserva Ecológica es_________________' },
    { text: 'La razón por la que nunca confiaría en un taxista porteño es_________________' },
    { text: 'Lo más macabro que he escuchado en la Plaza de Mayo es_________________' },
    { text: 'La cosa más cruel que he visto hacer a un hincha es_________________' },
    { text: 'Lo más inapropiado que he hecho en el Congreso es_________________' },
    { text: 'La peor manera de romper el aislamiento social es_________________' },
    { text: 'Lo más oscuro que he visto en el Riachuelo es_________________' },
    { text: 'La peor cosa que me ha pasado en Retiro es_________________' },
    { text: 'Lo más bizarro que he visto en el tren Sarmiento es_________________' },
    { text: 'La cosa más cruel que he escuchado en un juicio es_________________' },
    { text: 'Lo más inapropiado que he hecho en una villa es_________________' },
    { text: 'La peor cosa que he visto en el Puente de la Mujer es_________________' },
    { text: 'Lo más oscuro que he encontrado en el Jardín Japonés es_________________' },
    { text: 'La cosa más cruel que he hecho durante el toque de queda es_________________' },
    { text: 'Lo peor que he hecho en un piquete es_________________' },
    { text: 'La peor cosa que he visto en una protesta es_________________' },
    { text: 'Lo más oscuro que he visto en una misa es_________________' },
    { text: 'La cosa más cruel que he escuchado en un velorio es_________________' },
    { text: 'Lo peor que he dicho en una iglesia es_________________' },
    { text: 'La cosa más cruel que he hecho en una marcha es_________________' },
    { text: 'Lo más oscuro que he visto en el hospital Fernández es_________________' },
    { text: 'La peor cosa que me ha pasado en Constitución es_________________' },
    { text: 'Lo más bizarro que he visto en el Obelisco es_________________' },
    { text: 'La cosa más cruel que he dicho en un asado es_________________' },
    { text: 'Lo peor que he hecho en la cancha de River es_________________' },
    { text: 'La peor cosa que he visto en una villa miseria es_________________' },
    { text: 'Lo más oscuro que he hecho en una autopista es_________________' },
    { text: 'La cosa más cruel que he visto en el Colón es_________________' },
    { text: 'Lo peor que he escuchado en una parrilla es_________________' },
    { text: 'La cosa más cruel que he hecho en la playa es_________________' },
    { text: 'Lo más oscuro que he visto en la calle es_________________' },
    { text: 'La peor cosa que me ha pasado en un boliche es_________________' },
    { text: 'Lo más bizarro que he visto en el Tigre es_________________' },
    { text: 'La cosa más cruel que he escuchado en una feria es_________________' },
    { text: 'Lo peor que he dicho en un carnaval es_________________' },
    { text: 'La peor cosa que he visto en una manifestación es_________________' },
    { text: 'Lo más oscuro que he hecho en una cancha de fútbol es_________________' },
    { text: 'La cosa más cruel que he visto en un estadio es_________________' },
    { text: 'Lo peor que he hecho en un recital es_________________' },
    { text: 'La cosa más cruel que he dicho en un cumpleaños es_________________' },
    { text: 'Lo más oscuro que he visto en el aeropuerto de Ezeiza es_________________' },
    { text: 'La peor cosa que me ha pasado en la terminal de ómnibus es_________________' },
    { text: 'Lo más bizarro que he visto en una ruta es_________________' },
    { text: 'La cosa más cruel que he hecho en el zoológico es_________________' },
    { text: 'Lo peor que he escuchado en una estación de servicio es_________________' },
    { text: 'La cosa más cruel que he visto en una tienda es_________________' },
    { text: 'Lo más oscuro que he visto en el Teatro Colón es_________________' },
    { text: 'La peor cosa que me ha pasado en la Avenida 9 de Julio es_________________' },
    { text: 'Lo más bizarro que he encontrado en una feria es_________________' },
    { text: 'La cosa más cruel que he escuchado en la televisión es_________________' },
    { text: 'Lo peor que he hecho en la Facultad es_________________' },
    { text: 'Lo más escandaloso que he visto en el barrio de Palermo es_________________' },
    { text: 'La cosa más inapropiada que he hecho en el Obelisco es_________________' },
    { text: 'Lo más picante que he oído en un asado es_________________' },
    { text: 'El peor lugar para tener un encuentro íntimo es_________________' },
    { text: 'La cosa más inapropiada que he visto en la playa de Mar del Plata es_________________' },
    { text: 'Lo más atrevido que he hecho en el subte es_________________' },
    { text: 'La cosa más escandalosa que he escuchado en un taxi es_________________' },
    { text: 'Lo más inapropiado que he visto en una fiesta es_________________' },
    { text: 'El peor lugar para un encuentro romántico en Buenos Aires es_________________' },
    { text: 'Lo más atrevido que he dicho en una milonga es_________________' },
    { text: 'La cosa más inapropiada que he hecho en una villa es_________________' },
    { text: 'Lo más escandaloso que he hecho en un colectivo es_________________' },
    { text: 'El peor lugar para tener una cita en Buenos Aires es_________________' },
    { text: 'La cosa más inapropiada que he dicho en el trabajo es_________________' },
    { text: 'Lo más atrevido que he hecho en una cancha de fútbol es_________________' },
    { text: 'La cosa más escandalosa que he visto en un boliche es_________________' },
    { text: 'Lo más inapropiado que he dicho en una reunión familiar es_________________' },
    { text: 'El peor lugar para ser pillado en Buenos Aires es_________________' },
    { text: 'Lo más atrevido que he hecho en una librería es_________________' },
    { text: 'La cosa más inapropiada que he visto en una peña es_________________' },
    { text: 'Lo más escandaloso que he hecho en una piscina pública es_________________' },
    { text: 'El peor lugar para tener una aventura en Argentina es_________________' },
    { text: 'Lo más atrevido que he hecho en un recital es_________________' },
    { text: 'La cosa más inapropiada que he visto en el trabajo es_________________' },
    { text: 'Lo más escandaloso que he dicho en una entrevista de trabajo es_________________' },
    { text: 'El peor lugar para un chiste verde es_________________' },
    { text: 'La cosa más inapropiada que he hecho en una manifestación es_________________' },
    { text: 'Lo más atrevido que he visto en un parque público es_________________' },
    { text: 'La cosa más escandalosa que he hecho en una reunión social es_________________' },
    { text: 'Lo más inapropiado que he dicho en un tren es_________________' },
    { text: 'El peor lugar para hablar de temas íntimos es_________________' },
    { text: 'La cosa más inapropiada que he hecho en un supermercado es_________________' },
    { text: 'Lo más atrevido que he visto en un teatro es_________________' },
    { text: 'La cosa más escandalosa que he dicho en una iglesia es_________________' },
    { text: 'Lo más inapropiado que he hecho en un restaurante es_________________' },
    { text: 'El peor lugar para una despedida de soltero es_________________' },
    { text: 'La cosa más inapropiada que he visto en una clase es_________________' },
    { text: 'Lo más atrevido que he hecho en un taxi es_________________' },
    { text: 'La cosa más escandalosa que he hecho en una biblioteca es_________________' },
    { text: 'Lo más inapropiado que he dicho en una consulta médica es_________________' },
    { text: 'El peor lugar para una conversación picante es_________________' },
    { text: 'La cosa más inapropiada que he hecho en una plaza es_________________' },
    { text: 'Lo más atrevido que he visto en un cine es_________________' },
    { text: 'La cosa más escandalosa que he dicho en una boda es_________________' },
    { text: 'Lo más inapropiado que he hecho en una fiesta de fin de año es_________________' },
    { text: 'El peor lugar para un encuentro clandestino es_________________' },
    { text: 'La cosa más inapropiada que he visto en una feria es_________________' },
    { text: 'Lo más atrevido que he hecho en una feria de San Telmo es_________________' },
    { text: 'La cosa más escandalosa que he hecho en un hotel es_________________' },
    { text: 'Lo más inapropiado que he dicho en una cancha de Boca es_________________' },
    { text: 'Lo más arriesgado que he hecho en un boliche es_________________' },
    { text: 'La cosa más perversa que he visto en la Feria de Mataderos es_________________' },
    { text: 'Lo más provocador que he visto en una fiesta de egresados es_________________' },
    { text: 'El peor lugar para tener un momento íntimo en Buenos Aires es_________________' },
    { text: 'La cosa más atrevida que he hecho en la Costanera es_________________' },
    { text: 'Lo más escandaloso que he hecho en un club nocturno es_________________' },
    { text: 'La peor sorpresa que me ha dado una cita en el barrio de Palermo es_________________' },
    { text: 'Lo más íntimo que he visto en un recital es_________________' },
    { text: 'El lugar más inapropiado para una escena de película para adultos es_________________' },
    { text: 'Lo más subido de tono que he escuchado en una milonga es_________________' },
    { text: 'La cosa más desinhibida que he hecho en el Jardín Japonés es_________________' },
    { text: 'Lo peor que he visto en una fiesta de disfraces es_________________' },
    { text: 'La cosa más atrevida que he visto en el Rosedal es_________________' },
    { text: 'Lo más subido de tono que he hecho en una playa de Mar del Plata es_________________' },
    { text: 'La peor cosa que me ha pasado en una reunión de amigos es_________________' },
    { text: 'Lo más escandaloso que he visto en una parrilla es_________________' },
    { text: 'El lugar más vergonzoso para una escapada romántica en Buenos Aires es_________________' },
    { text: 'Lo más atrevido que he dicho en una fiesta de fin de año es_________________' },
    { text: 'La cosa más sensual que he visto en un taxi es_________________' },
    { text: 'Lo peor que he hecho en un boliche de Palermo es_________________' },
    { text: 'La cosa más provocadora que he hecho en una plaza es_________________' },
    { text: 'Lo más subido de tono que he visto en un casino es_________________' },
    { text: 'La peor broma que he hecho en una fiesta es_________________' },
    { text: 'Lo más arriesgado que he visto en la Plaza de Mayo es_________________' },
    { text: 'La cosa más subidita de tono que he hecho en una biblioteca es_________________' },
    { text: 'Lo peor que he visto en un espectáculo nocturno es_________________' },
    { text: 'La cosa más escandalosa que he hecho en el Centro Cultural Konex es_________________' },
    { text: 'Lo más atrevido que he visto en un club de tango es_________________' },
    { text: 'El peor lugar para una escena subida de tono en Buenos Aires es_________________' },
    { text: 'La cosa más explícita que he visto en el Jardín Botánico es_________________' },
    { text: 'Lo más desinhibido que he hecho en un restaurante es_________________' },
    { text: 'La peor cosa que he visto en un hotel de lujo es_________________' },
    { text: 'Lo más subido de tono que he hecho en una fiesta de cumpleaños es_________________' },
    { text: 'La cosa más arriesgada que he visto en una discoteca es_________________' },
    { text: 'Lo peor que me ha pasado en un bar de Buenos Aires es_________________' },
    { text: 'La cosa más provocativa que he hecho en el Obelisco es_________________' },
    { text: 'Lo más subido de tono que he visto en una feria es_________________' },
    { text: 'La peor broma que he hecho en una fiesta de fin de año es_________________' },
    { text: 'Lo más explícito que he visto en un show en vivo es_________________' },
    { text: 'La cosa más atrevida que he hecho en un bar de Palermo es_________________' },
    { text: 'Lo más escandaloso que he hecho en una plaza de Buenos Aires es_________________' },
    { text: 'La peor situación en la que he encontrado a alguien en el Rosedal es_________________' },
    { text: 'Lo más subido de tono que he hecho en una discoteca es_________________' },
    { text: 'La cosa más provocativa que he visto en una feria es_________________' },
    { text: 'Lo peor que he escuchado en una fiesta privada es_________________' },
    { text: 'La cosa más atrevida que he hecho en un club nocturno es_________________' },
    { text: 'Lo más subido de tono que he visto en una fiesta de disfraces es_________________' },
    { text: 'La peor situación que he vivido en un boliche de Buenos Aires es_________________' },
    { text: 'Lo más absurdo que he visto en un partido de fútbol en Argentina es_________________' },
    { text: 'La cosa más bizarra que he hecho en una fiesta de cumpleaños es_________________' },
    { text: 'Lo peor que he escuchado en una mesa de café en Buenos Aires es_________________' },
    { text: 'La cosa más ridícula que he visto en la Feria de San Telmo es_________________' },
    { text: 'Lo más incómodo que he hecho en una milonga es_________________' },
    { text: 'La peor excusa que he escuchado en un bar porteño es_________________' },
    { text: 'Lo más insólito que me ha pasado en un tren de Buenos Aires es_________________' },
    { text: 'La cosa más absurda que he visto en una marcha es_________________' },
    { text: 'Lo más raro que he hecho en un espectáculo en el Teatro Colón es_________________' },
    { text: 'La peor cosa que he visto en el Riachuelo es_________________' },
    { text: 'Lo más inesperado que he encontrado en el Jardín Botánico es_________________' },
    { text: 'La cosa más incómoda que he hecho en un bar de Palermo es_________________' },
    { text: 'Lo peor que he dicho en una clase de tango es_________________' },
    { text: 'La cosa más absurda que he hecho en un carnaval es_________________' },
    { text: 'Lo más inesperado que he visto en un partido de Boca-River es_________________' },
    { text: 'La peor situación que he vivido en una cola para un recital es_________________' },
    { text: 'Lo más raro que he hecho en una fiesta de egresados es_________________' },
    { text: 'La cosa más insólita que he visto en el Congreso es_________________' },
    { text: 'Lo peor que he visto en un espectáculo de magia es_________________' },
    { text: 'La cosa más absurda que he visto en un boliche es_________________' },
    { text: 'Lo más ridículo que he hecho en la Plaza de Mayo es_________________' },
    { text: 'La peor cosa que he escuchado en una conversación en la Costanera es_________________' },
    { text: 'Lo más extraño que he visto en el Jardín Japonés es_________________' },
    { text: 'La cosa más bizarra que he hecho en una parrilla es_________________' },
    { text: 'Lo peor que me ha pasado en una fiesta de Año Nuevo es_________________' },
    { text: 'La cosa más absurda que he hecho en el Zoo de Buenos Aires es_________________' },
    { text: 'Lo más incómodo que he visto en una fiesta de despedida de soltero es_________________' },
    { text: 'La peor cosa que he escuchado en un bar en San Telmo es_________________' },
    { text: 'Lo más ridículo que he hecho en una fiesta de disfraces es_________________' },
    { text: 'La cosa más insólita que he visto en el Teatro Colón es_________________' },
    { text: 'Lo peor que he visto en una manifestación es_________________' },
    { text: 'La cosa más absurda que he escuchado en una boda es_________________' },
    { text: 'Lo más extraño que he hecho en una reunión de amigos es_________________' },
    { text: 'La cosa más ridícula que he visto en un boliche de Palermo es_________________' },
    { text: 'Lo peor que he hecho en un recital de rock es_________________' },
    { text: 'La cosa más bizarra que he visto en una feria es_________________' },
    { text: 'Lo más inesperado que he hecho en el Obelisco es_________________' },
    { text: 'La peor situación que he vivido en una cita en Buenos Aires es_________________' },
    { text: 'Lo más ridículo que he visto en una plaza es_________________' },
    { text: 'La cosa más absurda que he hecho en una fiesta de fin de año es_________________' },
    { text: 'Lo peor que he escuchado en una peña es_________________' },
    { text: 'La cosa más rara que he visto en una fiesta en Villa Urquiza es_________________' },
    { text: 'Lo más bizarro que he hecho en una parrilla es_________________' },
    { text: 'La peor cosa que he visto en un espectáculo de comedia es_________________' },
    { text: 'Lo más inesperado que he visto en una feria de antigüedades es_________________' },
    { text: 'La cosa más absurda que he escuchado en una charla de café es_________________' },
    { text: 'Lo más raro que he visto en el Jardín Botánico es_________________' },
    { text: 'La peor situación que he vivido en una cola para un partido de fútbol es_________________' },
    { text: 'Lo más ridículo que he hecho en una fiesta en el barrio de Almagro es_________________' },
    { text: 'La cosa más bizarra que he visto en un partido de polo es_________________' },
    { text: 'Lo peor que he hecho en una fiesta de casamiento es_________________' },
    { text: 'La cosa más absurda que he hecho en un festival de cine es_________________' },
    { text: 'Lo más extraño que he visto en una fiesta de cumpleaños es_________________' },
    { text: 'La peor cosa que he escuchado en un bar en La Boca es_________________' },
    { text: 'Lo más ridículo que he hecho en una fiesta en el Rosedal es_________________' },
    { text: 'La cosa más bizarra que he visto en un espectáculo en el Luna Park es_________________' },
    { text: 'Lo peor que he visto en un show de magia es_________________' },
    { text: 'La cosa más absurda que he hecho en una reunión en Villa Devoto es_________________' },
    { text: 'Lo más inesperado que he visto en el barrio de Retiro es_________________' },
    { text: 'La peor situación que he vivido en un recital en el Estadio Monumental es_________________' },
    { text: 'Lo más ridículo que he visto en una fiesta en Villa Crespo es_________________' },
    { text: 'La cosa más bizarra que he hecho en una sala de teatro es_________________' },
    { text: 'Lo peor que he escuchado en una clase de yoga es_________________' },
    { text: 'La cosa más absurda que he visto en una fiesta de disfraces es_________________' },
    { text: 'Lo más raro que he hecho en una reunión en el barrio de Caballito es_________________' },
    { text: 'La peor cosa que he visto en una fiesta en la Avenida Corrientes es_________________' },
    { text: 'Lo más inesperado que he encontrado en un parque de diversiones es_________________' },
    { text: 'La cosa más ridícula que he hecho en un hotel de Buenos Aires es_________________' },
    { text: 'Lo más bizarro que he visto en un recital de música clásica es_________________' },
    { text: 'La peor situación que he vivido en una fiesta en la playa de Mar del Plata es_________________' },
    { text: 'Lo más absurdo que he hecho en una fiesta en el barrio de Monserrat es_________________' },
    { text: 'La cosa más inesperada que he visto en un festival de tango es_________________' },
    { text: 'Lo peor que he escuchado en una fiesta de cumpleaños es_________________' },
    { text: 'La cosa más ridícula que he visto en un partido de tenis es_________________' },
    { text: 'Lo más bizarro que he hecho en una fiesta en un boliche de Palermo es_________________' },
    { text: 'La peor situación que he vivido en un recital en el Estadio Luna Park es_________________' },
    { text: 'Lo más inesperado que he visto en una fiesta en el barrio de Belgrano es_________________' },
    { text: 'La cosa más absurda que he escuchado en un recital en el barrio de San Telmo es_________________' },
    { text: 'Lo peor que he hecho en una fiesta de despedida en el barrio de Caballito es_________________' },
    { text: 'La cosa más ridícula que he visto en una fiesta en Villa del Parque es_________________' },
    { text: 'Lo más bizarro que he encontrado en una fiesta en el barrio de Villa Luro es_________________' },
    { text: 'La peor cosa que he escuchado en una fiesta de amigos es_________________' },
    { text: 'Lo más inesperado que he hecho en una fiesta de fin de año es_________________' },
    { text: 'La cosa más absurda que he visto en un partido de rugby es_________________' },
    { text: 'Lo peor que he visto en una fiesta en el barrio de Flores es_________________' },
    { text: 'La cosa más ridícula que he hecho en un festival de rock es_________________' },
    { text: 'Lo más bizarro que he visto en un desfile de moda es_________________' },
    { text: 'La peor situación que he vivido en una fiesta de cumpleaños en el barrio de Núñez es_________________' },
    { text: 'Lo más inesperado que he hecho en un bar en el barrio de San Cristóbal es_________________' },
    { text: 'La cosa más absurda que he escuchado en una fiesta en el barrio de Villa Santa Rita es_________________' },
    { text: 'Lo peor que he visto en un espectáculo en el barrio de Villa del Parque es_________________' },
    { text: 'La cosa más ridícula que he visto en una fiesta en el barrio de Boedo es_________________' },
    { text: 'Lo más bizarro que he hecho en una fiesta en el barrio de Balvanera es_________________' },
    { text: 'La peor cosa que he escuchado en un bar en el barrio de La Boca es_________________' },
    { text: 'Lo más inesperado que he visto en un evento en el barrio de La Paternal es_________________' },
    { text: 'La cosa más absurda que he hecho en una fiesta en el barrio de Villa del Parque es_________________' },
    { text: 'Lo peor que he visto en una fiesta en el barrio de Parque Chacabuco es_________________' },
    { text: 'La cosa más ridícula que he visto en un bar en el barrio de San Nicolás es_________________' },
    { text: 'Lo más bizarro que he encontrado en una fiesta en el barrio de Palermo Soho es_________________' },
    { text: 'La peor situación que he vivido en una fiesta en el barrio de Chacarita es_________________' },
    { text: 'Lo más inesperado que he visto en una fiesta en el barrio de Villa Devoto es_________________' },
    { text: 'La cosa más absurda que he visto en una fiesta en el barrio de Villa Urquiza es_________________' },
    { text: 'Lo peor que he escuchado en un bar en el barrio de Villa Lugano es_________________' },
    { text: 'La cosa más ridícula que he hecho en una fiesta en el barrio de Villa Ortúzar es_________________' },
    { text: 'Lo más bizarro que he visto en una fiesta en el barrio de Villa del Parque es_________________' },
    { text: 'La peor cosa que he visto en una fiesta en el barrio de Villa Santa Rita es_________________' }
  ];

  for (const card of blackCards) {
    await prisma.blackCard.create({
      data: card
    });
  }

  console.log('Cartas negras agregadas a la base de datos');
}

main()
  .catch(e => {
    throw e;
  })
  .finally(async () => {
    await prisma.$disconnect();
  });
